default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost
  timeout: 5000

development:
  <<: *default
  database: kusorep-maker_dev

test:
  <<: *default
  database: kusorep-maker_test

production:
  url: <%= ENV['DATABASE_URL'] %>
